name: build android apk

env:
  VERSION: v1.12.25

on:
  workflow_dispatch:

jobs:

  android:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout SagerNet/sing-box
        uses: actions/checkout@v6
        with:
          repository: SagerNet/sing-box
          ref: ${{ env.VERSION }}
          fetch-depth: 0
          submodules: 'recursive'

      - name: Setup Go
        uses: actions/setup-go@v6
        with:
          go-version: ~1.25.8
          # go-version: ^1.25
          # check-latest: true # Always check for the latest patch release
          # cache: false

      - name: Setup Android NDK
        id: setup-ndk
        uses: nttld/setup-ndk@v1
        with:
          ndk-version: r28

      - name: Setup OpenJDK
        run: |-
          sudo apt update && sudo apt install -y openjdk-17-jdk-headless
          /usr/lib/jvm/java-17-openjdk-amd64/bin/java --version

      - name: Set tag
        run: git tag ${{ env.VERSION }} -f

      - name: Build library
        run: |-
          make lib_install
          export PATH="$PATH:$(go env GOPATH)/bin"
          make lib_android
        env:
          JAVA_HOME: /usr/lib/jvm/java-17-openjdk-amd64
          ANDROID_NDK_HOME: ${{ steps.setup-ndk.outputs.ndk-path }}

      - name: Gradle cache
        uses: actions/cache@v5
        with:
          path: ~/.gradle
          key: gradle-${{ hashFiles('**/*.gradle') }}

      - name: Change applicationId
        run: |
          sed -i 's/applicationId "io.nekohasekai.sfa"/applicationId "bgx.niubi"/' clients/android/app/build.gradle

      - name: Build sing-box apk
        run: |-
          mkdir -p ./clients/android/app/libs/
          cp -f  ./*.aar ./clients/android/app/libs/
          cd ./clients/android
          ./gradlew :app:assembleOtherRelease
        env:
          JAVA_HOME: /usr/lib/jvm/java-17-openjdk-amd64
          ANDROID_NDK_HOME: ${{ steps.setup-ndk.outputs.ndk-path }}
          LOCAL_PROPERTIES: ${{ secrets.LOCAL_PROPERTIES }}

      - name: Prepare upload
        run: |-
          mkdir -p dist
          cp clients/android/app/build/outputs/apk/other/release/*.apk dist

      - name: Upload artifact
        uses: actions/upload-artifact@v7
        with:
          name: binary-android-apks
          path: 'dist'   
