name: Build AX6000 ImmortalWrt 24.10 test
# AX6000 custom U-Boot layout

on:
  workflow_dispatch:

env:
  VERSION: v24.10.6

jobs:
  build:
    runs-on: ubuntu-latest
    if: github.event.repository.owner.id == github.event.sender.id

    steps:

    - name: Checkout
      uses: actions/checkout@v5

    - name: Clone source code
      run: |
        git clone -b ${{ env.VERSION }} --single-branch --depth=1 https://github.com/immortalwrt/immortalwrt.git immortalwrt-${{ env.VERSION }}

    - name: Restore AX6000 custom U-Boot layout
      run: |
        chmod +x "$GITHUB_WORKSPACE/immortalwrt/Redmi-AX6000-24.10/custom-U-Boot-layout.sh"
        cd immortalwrt-${{ env.VERSION }}
        "$GITHUB_WORKSPACE/immortalwrt/Redmi-AX6000-24.10/custom-U-Boot-layout.sh"
        sed -n '/^define Device\/xiaomi_redmi-router-ax6000$/,/^endef$/p' target/linux/mediatek/image/filogic.mk

    - name: Space show before
      run: df -hT

    - name: Use my config
      run: |
        cp -f "$GITHUB_WORKSPACE/immortalwrt/Redmi-AX6000-24.10/.config" immortalwrt-${{ env.VERSION }}/.config

    - name: Download package
      run: |
        cd immortalwrt-${{ env.VERSION }}
        echo "$(nproc) thread download"
        make defconfig
        grep -E '^CONFIG_TARGET_DEVICE_mediatek_filogic_DEVICE_xiaomi_redmi-router-ax6000.*=y' .config

    - name: Set variables
      run: |
        echo "TAG_DATE=$(date +%Y%m%d%H%M)" >> $GITHUB_ENV
      shell: bash
