name: Build ZN AuditPatch chisewaguri

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          repository: chisewaguri/ZN-AuditPatch
          ref: master
          submodules: "recursive"
          fetch-depth: 0

      - name: Setup Java
        uses: actions/setup-java@v4
        with:
          distribution: "temurin"
          java-version: 17

      - name: Setup Gradle
        uses: gradle/actions/setup-gradle@v4

      # - name: Build debug
      #   run: |
      #     chmod +x gradlew
      #     ./gradlew clean zipDebug
      #     mkdir debug
      #     unzip module/release/Audit-Patch-*-debug.zip -d debug

      # - name: Upload debug
      #   uses: actions/upload-artifact@v4
      #   with:
      #     name: Audit-Patch-debug
      #     path: "./debug/*"

      - name: Build release
        run: |
          chmod +x gradlew
          ./gradlew clean zipRelease
          # mkdir release
          # unzip module/release/Audit-Patch-*-release.zip -d release

      # - name: Upload release
      #   uses: actions/upload-artifact@v4
      #   with:
      #     name: Audit-Patch-release
      #     path: "./release/*"


      - name: Prepare artifact
        if: success()
        id: prepareArtifact
        run: |
          AuditPatchReleaseName=`ls module/release/Audit-Patch-*-release.zip | awk -F '(/|.zip)' '{print $3}'` && echo "AuditPatchReleaseName=$AuditPatchReleaseName" >> $GITHUB_OUTPUT
          unzip module/release/Audit-Patch-*-release.zip -d Audit-Patch-release


      - name: Upload release
        uses: actions/upload-artifact@v4
        with:
          name: ${{ steps.prepareArtifact.outputs.AuditPatchReleaseName }}
          path: "./Audit-Patch-release/*"












