name: buildSB

env:
  VERSION: v1.10.1
  ENV_LINUX: CGO_ENABLED=0 GOOS=linux GOARCH=amd64 GOAMD64=v3
  ENV_WINDOWS: CGO_ENABLED=0 GOOS=windows GOARCH=amd64 GOAMD64=v3
  ENV_LINUX_V2: CGO_ENABLED=0 GOOS=linux GOARCH=amd64 GOAMD64=v2
  ENV_WINDOWS_V2: CGO_ENABLED=0 GOOS=windows GOARCH=amd64 GOAMD64=v2
  ENV_LINUX_V4: CGO_ENABLED=0 GOOS=linux GOARCH=amd64 GOAMD64=v4
  ENV_WINDOWS_V4: CGO_ENABLED=0 GOOS=windows GOARCH=amd64 GOAMD64=v4
  ENV_LINUX_V1: CGO_ENABLED=0 GOOS=linux GOARCH=amd64 GOAMD64=v1
  ENV_WINDOWS_V1: CGO_ENABLED=0 GOOS=windows GOARCH=amd64 GOAMD64=v1
  TAG_LINUX: with_gvisor,with_reality_server,with_quic,with_utls,with_ech,with_dhcp,with_wireguard,with_acme,with_clash_api,with_v2ray_api,with_grpc
  TAG_WINDOWS: with_gvisor,with_reality_server,with_quic,with_utls,with_ech,with_dhcp,with_wireguard,with_acme,with_clash_api,with_v2ray_api,with_grpc

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Setup Go
      uses: actions/setup-go@v5
      with:
        go-version: ^1.23
        cache: false

    - name: git clone
      run: |
        git clone -b ${{ env.VERSION }} https://github.com/SagerNet/sing-box

    - name: Build Linux V3
      run: |
        cd sing-box
        go env -w ${{ env.ENV_LINUX }}
        go build -tags ${{ env.TAG_LINUX }} -v -o sing-box -trimpath -ldflags "-X 'github.com/sagernet/sing-box/constant.Version=${{ env.VERSION }}' -s -w -buildid=" ./cmd/sing-box
        cd ..

    - name: Build Windows V3
      run: |
        cd sing-box
        go env -w ${{ env.ENV_WINDOWS }}
        go build -tags ${{ env.TAG_WINDOWS }} -v -o sing-box.exe -trimpath -ldflags "-X 'github.com/sagernet/sing-box/constant.Version=${{ env.VERSION }}' -s -w -buildid=" ./cmd/sing-box
        cd ..

    - name: Build Linux V2
      run: |
        cd sing-box
        go env -w ${{ env.ENV_LINUX_V2 }}
        go build -tags ${{ env.TAG_LINUX }} -v -o sing-box-v2 -trimpath -ldflags "-X 'github.com/sagernet/sing-box/constant.Version=${{ env.VERSION }}' -s -w -buildid=" ./cmd/sing-box
        cd ..

    - name: Build Windows V2
      run: |
        cd sing-box
        go env -w ${{ env.ENV_WINDOWS_V2 }}
        go build -tags ${{ env.TAG_WINDOWS }} -v -o sing-box-v2.exe -trimpath -ldflags "-X 'github.com/sagernet/sing-box/constant.Version=${{ env.VERSION }}' -s -w -buildid=" ./cmd/sing-box
        cd ..

    - name: Build Linux V4
      run: |
        cd sing-box
        go env -w ${{ env.ENV_LINUX_V4 }}
        go build -tags ${{ env.TAG_LINUX }} -v -o sing-box-v4 -trimpath -ldflags "-X 'github.com/sagernet/sing-box/constant.Version=${{ env.VERSION }}' -s -w -buildid=" ./cmd/sing-box
        cd ..

    - name: Build Windows V4
      run: |
        cd sing-box
        go env -w ${{ env.ENV_WINDOWS_V4 }}
        go build -tags ${{ env.TAG_WINDOWS }} -v -o sing-box-v4.exe -trimpath -ldflags "-X 'github.com/sagernet/sing-box/constant.Version=${{ env.VERSION }}' -s -w -buildid=" ./cmd/sing-box
        cd ..

    - name: Build Linux V1
      run: |
        cd sing-box
        go env -w ${{ env.ENV_LINUX_V1 }}
        go build -tags ${{ env.TAG_LINUX }} -v -o sing-box-v1 -trimpath -ldflags "-X 'github.com/sagernet/sing-box/constant.Version=${{ env.VERSION }}' -s -w -buildid=" ./cmd/sing-box
        cd ..

    - name: Build Windows V1
      run: |
        cd sing-box
        go env -w ${{ env.ENV_WINDOWS_V1 }}
        go build -tags ${{ env.TAG_WINDOWS }} -v -o sing-box-v1.exe -trimpath -ldflags "-X 'github.com/sagernet/sing-box/constant.Version=${{ env.VERSION }}' -s -w -buildid=" ./cmd/sing-box
        cd ..

    - name: List built files
      run: |
        cd sing-box
        ls -l sing-box sing-box.exe sing-box-v2 sing-box-v2.exe sing-box-v4 sing-box-v4.exe sing-box-v1 sing-box-v1.exe
        cd ..

    - name: Package
      run: |
        mkdir sb-${{ env.VERSION }}
        cp sing-box/sing-box sb-${{ env.VERSION }}/
        cp sing-box/sing-box.exe sb-${{ env.VERSION }}/
        cp sing-box/sing-box-v2 sb-${{ env.VERSION }}/
        cp sing-box/sing-box-v2.exe sb-${{ env.VERSION }}/
        cp sing-box/sing-box-v4 sb-${{ env.VERSION }}/
        cp sing-box/sing-box-v4.exe sb-${{ env.VERSION }}/
        cp sing-box/sing-box-v1 sb-${{ env.VERSION }}/
        cp sing-box/sing-box-v1.exe sb-${{ env.VERSION }}/
        tar -zcvf sb-${{ env.VERSION }}.tar.gz sb-${{ env.VERSION }}

    - name: Upload
      uses: svenstaro/upload-release-action@v2
      with:
        repo_token: ${{ secrets.GITHUB_TOKEN }}
        tag: ${{ env.VERSION }}
        file: sb-${{ env.VERSION }}.tar.gz
        asset_name: sb-${{ env.VERSION }}.tar.gz
        prerelease: true
        overwrite: false
