name: Build iPerf for Windows

env:
  VERSION: 3.18

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: windows-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Install Cygwin
      run: |
        choco install cygwin
        choco install cygwin --params "/InstallDir:C:\\cygwin"
        choco install cygwin --params "/Packages:make,git,gcc-core,gcc-g++,libtool,automake,autoconf"

    - name: Set Cygwin Path
      run: |
        echo "C:\\cygwin\\bin" >> $GITHUB_PATH

    - name: Git clone iperf
      run: |
        C:\\cygwin\\bin\\bash.exe -lc "git clone -b ${{ env.VERSION }} https://github.com/esnet/iperf"

    - name: Build iPerf for Windows
      run: |
        C:\\cygwin\\bin\\bash.exe -lc "cd iperf && ./autogen.sh && ./configure && make"

    - name: Set variables
      run: |
        echo "TAG_DATE=$(date +%Y%m%d%H%M)" >> $GITHUB_ENV
      shell: bash

    - name: Package
      run: |
        mkdir iperf-${{ env.VERSION }}-${{ env.TAG_DATE }}
        cp iperf/src/iperf3.exe iperf-${{ env.VERSION }}-${{ env.TAG_DATE }}
        zip -r iperf-${{ env.VERSION }}-${{ env.TAG_DATE }}.zip iperf-${{ env.VERSION }}-${{ env.TAG_DATE }}

    - name: Upload
      uses: svenstaro/upload-release-action@v2
      with:
        repo_token: ${{ secrets.GITHUB_TOKEN }}
        tag: iperf-${{ env.VERSION }}-${{ env.TAG_DATE }}
        file: iperf-${{ env.VERSION }}-${{ env.TAG_DATE }}.zip
        asset_name: iperf-${{ env.VERSION }}-${{ env.TAG_DATE }}.zip
        prerelease: true
        overwrite: false
