name: Build iPerf for Windows

env:
  VERSION: 3.18

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: windows-latest
    
    steps:
    # Step 1: Checkout the repository
    - name: Checkout code
      uses: actions/checkout@v2
    
    # Step 2: Set up Cygwin environment
    - name: Install Cygwin
      shell: bash
      run: |
        # Download the Cygwin installer
        curl -o setup-x86_64.exe https://cygwin.com/setup-x86_64.exe
        
        # Run the Cygwin setup to install required packages
        start /wait setup-x86_64.exe -q -P gcc-core,gcc-g++,make,git,wget

    # Step 3: Clone the iperf repository
    - name: Clone the iperf repository
      shell: bash
      run: |
        # Clone the iperf repository
        git clone -b ${{ env.VERSION }} https://github.com/esnet/iperf
        cd iperf
        
    # Step 4: Build iperf
    - name: Build iperf
      shell: bash
      run: |
        cd iperf
        ./configure CFLAGS="-static" CXXFLAGS="-static"
        make

    # Step 5: Set environment variable for packaging
    - name: Set variables
      run: |
        echo "TAG_DATE=$(date +%Y%m%d%H%M)" >> $GITHUB_ENV
      shell: bash

    # Step 6: Package the build
    - name: Package
      run: |
        mkdir iperf-${{ env.VERSION }}-${{ env.TAG_DATE }}
        cp iperf/src/iperf3.exe iperf-${{ env.VERSION }}-${{ env.TAG_DATE }}
        zip -r iperf-${{ env.VERSION }}-${{ env.TAG_DATE }}.zip iperf-${{ env.VERSION }}-${{ env.TAG_DATE }}
        
    # Step 7: Upload release
    - name: Upload
      uses: svenstaro/upload-release-action@v2
      with:
        repo_token: ${{ secrets.GITHUB_TOKEN }}
        tag: iperf-${{ env.VERSION }}-${{ env.TAG_DATE }}
        file: iperf-${{ env.VERSION }}-${{ env.TAG_DATE }}.zip
        asset_name: iperf-${{ env.VERSION }}-${{ env.TAG_DATE }}.zip
        prerelease: true
        overwrite: false
