name: Build uboot AX6000

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-20.04
    if: github.event.repository.owner.id == github.event.sender.id

    steps:

    - name: Initialization environment
      env:
        DEBIAN_FRONTEND: noninteractive
      run: |
        sudo -E apt-get update
        sudo -E apt-get install -y gcc-aarch64-linux-gnu build-essential flex bison libssl-dev device-tree-compiler

    - name: Clone source code
      run: |
        git clone --depth=1 https://github.com/hanwckf/bl-mt798x.git

    - name: Space show before
      run: df -hT

    - name: Build Uboot AX6000
      run: |
        cd bl-mt798x
        SOC=mt7986 BOARD=redmi_ax6000 MULTI_LAYOUT=1 ./build.sh

    - name: Set variables
      run: |
        echo "TAG_DATE=$(date +%Y%m%d%H%M)" >> $GITHUB_ENV
      shell: bash

    - name: Package Firmware
      run: |
        tar -zcvf Redmi-AX6000-Uboot-${{ env.TAG_DATE }}.tar.gz bl-mt798x/output

    - name: Space show after
      run: df -hT

    - name: Upload
      uses: svenstaro/upload-release-action@v2
      with:
        repo_token: ${{ secrets.GITHUB_TOKEN }}
        tag: Redmi-AX6000-Uboot-${{ env.TAG_DATE }}
        file: Redmi-AX6000-Uboot-${{ env.TAG_DATE }}.tar.gz
        asset_name: Redmi-AX6000-Uboot-${{ env.TAG_DATE }}.tar.gz
        prerelease: true
        overwrite: false
