name: buildSB

env:
  ENV_LINUX: CGO_ENABLED=0 GOOS=linux GOARCH=amd64 GOAMD64=v3
  ENV_WINDOWS: CGO_ENABLED=0 GOOS=windows GOARCH=amd64 GOAMD64=v3
  ENV_LINUX_V2: CGO_ENABLED=0 GOOS=linux GOARCH=amd64 GOAMD64=v2
  ENV_WINDOWS_V2: CGO_ENABLED=0 GOOS=windows GOARCH=amd64 GOAMD64=v2
  TAG_LINUX: with_gvisor,with_reality_server,with_quic,with_utls,with_ech,with_dhcp,with_wireguard,with_acme,with_clash_api,with_v2ray_api,with_grpc
  TAG_WINDOWS: with_gvisor,with_reality_server,with_quic,with_utls,with_ech,with_dhcp,with_wireguard,with_acme,with_clash_api,with_v2ray_api,with_grpc

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Setup Go
      uses: actions/setup-go@v5
      with:
        go-version: '1.22'
        cache: false

    - name: go build
      run: |
        export VERSION=v1.9.7
        git clone -b $VERSION https://github.com/SagerNet/sing-box
        cd sing-box
        go env -w ${{ env.ENV_LINUX }}
        go build -tags ${{ env.TAG_LINUX }} -v -o sing-box -trimpath -ldflags "-X 'github.com/sagernet/sing-box/constant.Version=${VERSION}' -s -w -buildid=" ./cmd/sing-box
        go env -w ${{ env.ENV_WINDOWS }}
        go build -tags ${{ env.TAG_WINDOWS }} -v -o sing-box.exe -trimpath -ldflags "-X 'github.com/sagernet/sing-box/constant.Version=${VERSION}' -s -w -buildid=" ./cmd/sing-box
        go env -w ${{ env.ENV_LINUX_V2 }}
        go build -tags ${{ env.TAG_LINUX }} -v -o sing-box-v2 -trimpath -ldflags "-X 'github.com/sagernet/sing-box/constant.Version=${VERSION}' -s -w -buildid=" ./cmd/sing-box
        go env -w ${{ env.ENV_WINDOWS_V2 }}
        go build -tags ${{ env.TAG_WINDOWS }} -v -o sing-box-v2.exe -trimpath -ldflags "-X 'github.com/sagernet/sing-box/constant.Version=${VERSION}' -s -w -buildid=" ./cmd/sing-box

    - name: List built files
      run: |
        ls -l sing-box sing-box.exe sing-box-v2 sing-box-v2.exe

    - name: Upload files
      uses: actions/upload-artifact@v4
      with:
        name: sing-box
        path: |
          sing-box/sing-box
          sing-box/sing-box.exe
          sing-box/sing-box-v2
          sing-box/sing-box-v2.exe
